#!/bin/sh -e

##
## Keep up to date if someone else added/removed/updated a package
##

packageLockChanged=$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD \
  | grep --count "package-lock.json" \
)

if [ "$packageLockChanged" != "0" ]; then
  npm run setup -- --no-audit
fi
