#!/bin/bash -e

currentBranch=$(git rev-parse --abbrev-ref HEAD)

# If the branch doesn't exist in the remote repository, use 'main' as reference
if ! git ls-remote --heads origin | grep -q "refs/heads/$currentBranch"; then
  currentBranch='main'
fi

lastPushedCommit=$(git rev-parse "origin/$currentBranch")

lerna run "test,typecheck,lint" --since "$lastPushedCommit" \
  --concurrency 4 \
  --include-dependents
