#!/bin/sh

# Exit script if any statement returns a non-true return value
set -e

# Dont run in CI environment, for ex. when pushing version update
# via "semantic-release".
if [ -n "$CI" ]; then exit 0; fi

npm run typecheck
npm run lint
npm run test
